spring:
    application:
        name: MCQ-extractor
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        # active: dev
    datasource:
        url: jdbc:h2:~/workspaces/data/mcq;DB_CLOSE_DELAY=-1
        name:
        username: mcq
        password:
    jpa:
        hibernate:
                  ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
server:
    port: 8080

